### PR TITLE
fix 'np.float/np.complex depreciated'

### PR DESCRIPTION
**Pull request by weimin-liu**
- These aliases have been depreciated for the builtin types since NumPy 1.20.
- The machine we have produces file name 'ImagingInfo.xml' instead of 'scan.xml'

### CODE REVIEW

**Review by delsuc — APPROVED** [review]
Hi @weimin-liu ,
Thanks for the addition, are you doing MSImaging ?

**Review by delsuc — APPROVED** [review]
I did not know - this part is quite old in the code.
I believe there are other places where this happens...(but probably not a big deal)

I'll merge every thing soon - but let me finish another project.

**Comment by weimin-liu** [comment]
> Hi @weimin-liu ,
> Thanks for the addition, are you doing MSImaging ?

Hi @delsuc, yes, we are doing MSImaging in our lab, and the setup we use is a 7T sol­ariX XR FT-ICR-MS coupled to a MALDI source equipped with a Smart­beam II laser (Bruker Daltonik, Bre­men), which produces the data with `ImagingInfo.xml` instead of `scan.xml`.

**Comment by weimin-liu** [comment]
> I did not know - this part is quite old in the code. I believe there are other places where this happens...(but probably not a big deal)
> 
> I'll merge every thing soon - but let me finish another project.

Thanks. it's actually quite annoying when you have `numpy >= 1.20` installed, since the program just fails because there is  already no such aliases in the `numpy` library.

**Comment by delsuc** [comment]
@weimin-liu ,
Thanks again for your correction,  I found a couple of places where I could clean the type.
 
Also, I added a line in Solarix.py to also store the `ImagingInfo.xml` file internaly in the .msh5 file.
The idea is to have all metadata in the composite .msh5 file - regaredless we have a immediate usage or not...

Could you try if works for you...
(I am still struggelling to clean-up every thing (mostly the notebooks) for the next release)

**Pull request merged**
